// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even - valued terms.
// Sum is  4613732


#include <iostream>
using namespace std;

int fib()
{
	int firstNumber = 1, secondNumber = 2, nextNumber=0;
	int sumOfEvenNumbers = 2;

	while (nextNumber <= 4000000)
	{
		nextNumber = firstNumber + secondNumber;
		firstNumber = secondNumber;
		secondNumber = nextNumber;
		if (nextNumber % 2 == 0 && nextNumber <= 4000000)
		{
			sumOfEvenNumbers += nextNumber;
		}
		if (nextNumber > 4000000)
		{
			break;
		}
		std::cout << nextNumber << endl;
	}
	return sumOfEvenNumbers;
}

int main()
{
	cout <<"Sum of Even numbers is : "<< fib();
	return 0;
}
